name: Deploy Astro to Azure Static Web App

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Bun
        run: |
          curl https://install.bun.sh | bash

      - name: Install dependencies
        run: bun install

      - name: Build Astro for Production
        run: bun build

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_VICTORIOUS_PLANT_017C82903 }}

      - name: Upload deploy package
        uses: azure/staticwebapp@v2
        with:
          action: "upload"
          resourceGroup: "jaa198-static-web-app-01"
          appServiceName: "jarmer-portfolio-v2"
          location: "Global"
          slot: "main"
          appName: "James Armer Portfolio"
          customZipFile: "dist.zip"

      - name: Deploy to Azure Static Web App
        uses: azure/staticwebapp@v2
        with:
          action: "run-command"
          resourceGroup: "jaa198-static-web-app-01"
          appServiceName: "jarmer-portfolio-v2"
          location: "Global"
          slot: "main"
          appName: "James Armer Portfolio"
          commands: |
            # You can run build or deploy commands here specific to your needs
